nelmio_cors:
    defaults:
        allow_credentials: true
        # allow_credentials: false
        allow_origin: ['%env(CORS_ALLOW_ORIGIN)%']
        allow_headers: ['Accept','Authorization','Content-Type']
        allow_methods: ['POST', 'OPTIONS', 'GET', 'DELETE','PUT']
        expose_headers: []
        max_age: 0
        hosts: []
        # origin_regex: false
        origin_regex: true
        forced_allow_origin_value: ~
        skip_same_as_origin: true
    paths:
        '^/api/':
            allow_origin: ['%env(CORS_ALLOW_ORIGIN)%']
            allow_headers: ['Accept','Authorization','Content-Type']
            allow_methods: ['POST', 'OPTIONS','PUT', 'GET', 'DELETE']
            expose_headers: ['*']
            max_age: 100
        '^/':
            origin_regex: true
            allow_origin: ['%env(CORS_ALLOW_ORIGIN)%']
            allow_headers: ['Accept', Authorization,'Content-Type']
            allow_methods: ['POST', 'OPTIONS', 'GET', 'DELETE', 'PUT']
            max_age: 100
            hosts: ['^api\.']
