nelmio_cors:
    defaults:
        allow_credentials: true
        allow_origin: ['http://127.0.0.1:5500']
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
        allow_headers: ['Content-Type']
        expose_headers: ['Link']
        max_age: 3600
   
        
      
